// Code generated by generate.go. DO NOT EDIT.

package perpetua

import (
	"image/color"

	internalcolor "github.com/perpetuatheme/perpetua/internal/color"
)

type dark struct{}

var Dark Palette = dark{}

func (dark) Name() string {
	return "Dark"
}

func (dark) Red() Color {
	return Color{
		Name:  "Red",
		Index: 0,
		hex:   "#ff9d94",
		rgb:   color.RGBA{R: 255, G: 157, B: 148, A: 255},
		okhsl: internalcolor.Okhsl{H: 25.31, S: 100, L: 76},
	}
}

func (dark) Orange() Color {
	return Color{
		Name:  "Orange",
		Index: 1,
		hex:   "#ffa353",
		rgb:   color.RGBA{R: 255, G: 163, B: 83, A: 255},
		okhsl: internalcolor.Okhsl{H: 59.34, S: 100, L: 76},
	}
}

func (dark) Yellow() Color {
	return Color{
		Name:  "Yellow",
		Index: 2,
		hex:   "#dfb800",
		rgb:   color.RGBA{R: 223, G: 184, B: 0, A: 255},
		okhsl: internalcolor.Okhsl{H: 93.37, S: 100, L: 76},
	}
}

func (dark) Lime() Color {
	return Color{
		Name:  "Lime",
		Index: 3,
		hex:   "#90d400",
		rgb:   color.RGBA{R: 144, G: 212, B: 0, A: 255},
		okhsl: internalcolor.Okhsl{H: 129.15, S: 100, L: 76},
	}
}

func (dark) Green() Color {
	return Color{
		Name:  "Green",
		Index: 4,
		hex:   "#00dca0",
		rgb:   color.RGBA{R: 0, G: 220, B: 160, A: 255},
		okhsl: internalcolor.Okhsl{H: 164.93, S: 100, L: 76},
	}
}

func (dark) Turquoise() Color {
	return Color{
		Name:  "Turquoise",
		Index: 5,
		hex:   "#00d8cb",
		rgb:   color.RGBA{R: 0, G: 216, B: 203, A: 255},
		okhsl: internalcolor.Okhsl{H: 187.1225, S: 100, L: 76},
	}
}

func (dark) Cyan() Color {
	return Color{
		Name:  "Cyan",
		Index: 6,
		hex:   "#00d3eb",
		rgb:   color.RGBA{R: 0, G: 211, B: 235, A: 255},
		okhsl: internalcolor.Okhsl{H: 209.315, S: 100, L: 76},
	}
}

func (dark) Cerulean() Color {
	return Color{
		Name:  "Cerulean",
		Index: 7,
		hex:   "#56caff",
		rgb:   color.RGBA{R: 86, G: 202, B: 255, A: 255},
		okhsl: internalcolor.Okhsl{H: 231.5075, S: 100, L: 76},
	}
}

func (dark) Blue() Color {
	return Color{
		Name:  "Blue",
		Index: 8,
		hex:   "#8bbfff",
		rgb:   color.RGBA{R: 139, G: 191, B: 255, A: 255},
		okhsl: internalcolor.Okhsl{H: 253.7, S: 100, L: 76},
	}
}

func (dark) Violet() Color {
	return Color{
		Name:  "Violet",
		Index: 9,
		hex:   "#b6b1ff",
		rgb:   color.RGBA{R: 182, G: 177, B: 255, A: 255},
		okhsl: internalcolor.Okhsl{H: 286.6025, S: 100, L: 76},
	}
}

func (dark) Lavender() Color {
	return Color{
		Name:  "Lavender",
		Index: 10,
		hex:   "#ea95ff",
		rgb:   color.RGBA{R: 234, G: 149, B: 255, A: 255},
		okhsl: internalcolor.Okhsl{H: 319.505, S: 100, L: 76},
	}
}

func (dark) Pink() Color {
	return Color{
		Name:  "Pink",
		Index: 11,
		hex:   "#ff95c4",
		rgb:   color.RGBA{R: 255, G: 149, B: 196, A: 255},
		okhsl: internalcolor.Okhsl{H: 352.4075, S: 100, L: 76},
	}
}

func (dark) RedBack() Color {
	return Color{
		Name:  "Red Back",
		Index: 12,
		hex:   "#960d18",
		rgb:   color.RGBA{R: 150, G: 13, B: 24, A: 255},
		okhsl: internalcolor.Okhsl{H: 25.31, S: 97, L: 34},
	}
}

func (dark) OrangeBack() Color {
	return Color{
		Name:  "Orange Back",
		Index: 13,
		hex:   "#763f02",
		rgb:   color.RGBA{R: 118, G: 63, B: 2, A: 255},
		okhsl: internalcolor.Okhsl{H: 59.34, S: 97, L: 34},
	}
}

func (dark) YellowBack() Color {
	return Color{
		Name:  "Yellow Back",
		Index: 14,
		hex:   "#5f4e03",
		rgb:   color.RGBA{R: 95, G: 78, B: 3, A: 255},
		okhsl: internalcolor.Okhsl{H: 93.37, S: 97, L: 34},
	}
}

func (dark) LimeBack() Color {
	return Color{
		Name:  "Lime Back",
		Index: 15,
		hex:   "#3c5a07",
		rgb:   color.RGBA{R: 60, G: 90, B: 7, A: 255},
		okhsl: internalcolor.Okhsl{H: 129.15, S: 97, L: 34},
	}
}

func (dark) GreenBack() Color {
	return Color{
		Name:  "Green Back",
		Index: 16,
		hex:   "#085e43",
		rgb:   color.RGBA{R: 8, G: 94, B: 67, A: 255},
		okhsl: internalcolor.Okhsl{H: 164.93, S: 97, L: 34},
	}
}

func (dark) TurquoiseBack() Color {
	return Color{
		Name:  "Turquoise Back",
		Index: 17,
		hex:   "#045c56",
		rgb:   color.RGBA{R: 4, G: 92, B: 86, A: 255},
		okhsl: internalcolor.Okhsl{H: 187.1225, S: 97, L: 34},
	}
}

func (dark) CyanBack() Color {
	return Color{
		Name:  "Cyan Back",
		Index: 18,
		hex:   "#035a65",
		rgb:   color.RGBA{R: 3, G: 90, B: 101, A: 255},
		okhsl: internalcolor.Okhsl{H: 209.315, S: 97, L: 34},
	}
}

func (dark) CeruleanBack() Color {
	return Color{
		Name:  "Cerulean Back",
		Index: 19,
		hex:   "#035776",
		rgb:   color.RGBA{R: 3, G: 87, B: 118, A: 255},
		okhsl: internalcolor.Okhsl{H: 231.5075, S: 97, L: 34},
	}
}

func (dark) BlueBack() Color {
	return Color{
		Name:  "Blue Back",
		Index: 20,
		hex:   "#034f95",
		rgb:   color.RGBA{R: 3, G: 79, B: 149, A: 255},
		okhsl: internalcolor.Okhsl{H: 253.7, S: 97, L: 34},
	}
}

func (dark) VioletBack() Color {
	return Color{
		Name:  "Violet Back",
		Index: 21,
		hex:   "#5213c6",
		rgb:   color.RGBA{R: 82, G: 19, B: 198, A: 255},
		okhsl: internalcolor.Okhsl{H: 286.6025, S: 97, L: 34},
	}
}

func (dark) LavenderBack() Color {
	return Color{
		Name:  "Lavender Back",
		Index: 22,
		hex:   "#7c0493",
		rgb:   color.RGBA{R: 124, G: 4, B: 147, A: 255},
		okhsl: internalcolor.Okhsl{H: 319.505, S: 97, L: 34},
	}
}

func (dark) PinkBack() Color {
	return Color{
		Name:  "Pink Back",
		Index: 23,
		hex:   "#8f0259",
		rgb:   color.RGBA{R: 143, G: 2, B: 89, A: 255},
		okhsl: internalcolor.Okhsl{H: 352.4075, S: 97, L: 34},
	}
}

func (dark) Base0() Color {
	return Color{
		Name:  "Base 0",
		Index: 24,
		hex:   "#14171b",
		rgb:   color.RGBA{R: 20, G: 23, B: 27, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 9, L: 10},
	}
}

func (dark) Base1() Color {
	return Color{
		Name:  "Base 1",
		Index: 25,
		hex:   "#1a1e22",
		rgb:   color.RGBA{R: 26, G: 30, B: 34, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 10, L: 13},
	}
}

func (dark) Base2() Color {
	return Color{
		Name:  "Base 2",
		Index: 26,
		hex:   "#21252a",
		rgb:   color.RGBA{R: 33, G: 37, B: 42, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 11, L: 16},
	}
}

func (dark) Base3() Color {
	return Color{
		Name:  "Base 3",
		Index: 27,
		hex:   "#33383d",
		rgb:   color.RGBA{R: 51, G: 56, B: 61, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 9, L: 24},
	}
}

func (dark) Base4() Color {
	return Color{
		Name:  "Base 4",
		Index: 28,
		hex:   "#464b51",
		rgb:   color.RGBA{R: 70, G: 75, B: 81, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 8, L: 32},
	}
}

func (dark) Base5() Color {
	return Color{
		Name:  "Base 5",
		Index: 29,
		hex:   "#595f65",
		rgb:   color.RGBA{R: 89, G: 95, B: 101, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 7, L: 40},
	}
}

func (dark) Over0() Color {
	return Color{
		Name:  "Over 0",
		Index: 30,
		hex:   "#6d7378",
		rgb:   color.RGBA{R: 109, G: 115, B: 120, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 6, L: 48},
	}
}

func (dark) Over1() Color {
	return Color{
		Name:  "Over 1",
		Index: 31,
		hex:   "#82878c",
		rgb:   color.RGBA{R: 130, G: 135, B: 140, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 5, L: 56},
	}
}

func (dark) Over2() Color {
	return Color{
		Name:  "Over 2",
		Index: 32,
		hex:   "#989ca0",
		rgb:   color.RGBA{R: 152, G: 156, B: 160, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 4, L: 64},
	}
}

func (dark) Text0() Color {
	return Color{
		Name:  "Text 0",
		Index: 33,
		hex:   "#dcdddd",
		rgb:   color.RGBA{R: 220, G: 221, B: 221, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 1, L: 88},
	}
}

func (dark) Text1() Color {
	return Color{
		Name:  "Text 1",
		Index: 34,
		hex:   "#c5c7c8",
		rgb:   color.RGBA{R: 197, G: 199, B: 200, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 2, L: 80},
	}
}

func (dark) Text2() Color {
	return Color{
		Name:  "Text 2",
		Index: 35,
		hex:   "#aeb1b4",
		rgb:   color.RGBA{R: 174, G: 177, B: 180, A: 255},
		okhsl: internalcolor.Okhsl{H: 248.151875, S: 3, L: 72},
	}
}
