// Code generated by generate.go. DO NOT EDIT.

package perpetua

import (
	"image/color"

	internalcolor "github.com/perpetuatheme/go/internal/color"
)

type light struct{}

var Light Palette = light{}

func (light) Name() string {
	return "Light"
}

func (light) Red() Color {
	return Color{
		Name:  "Red",
		Index: 0,
		hex:   "#dd0c25",
		rgb:   color.RGBA{R: 221, G: 12, B: 37, A: 255},
		okhsl: internalcolor.Okhsl{H: 25.31, S: 99, L: 50},
	}
}

func (light) Orange() Color {
	return Color{
		Name:  "Orange",
		Index: 1,
		hex:   "#af6001",
		rgb:   color.RGBA{R: 175, G: 96, B: 1, A: 255},
		okhsl: internalcolor.Okhsl{H: 59.34, S: 99, L: 50},
	}
}

func (light) Yellow() Color {
	return Color{
		Name:  "Yellow",
		Index: 2,
		hex:   "#8e7502",
		rgb:   color.RGBA{R: 142, G: 117, B: 2, A: 255},
		okhsl: internalcolor.Okhsl{H: 93.37, S: 99, L: 50},
	}
}

func (light) Lime() Color {
	return Color{
		Name:  "Lime",
		Index: 3,
		hex:   "#5a8705",
		rgb:   color.RGBA{R: 90, G: 135, B: 5, A: 255},
		okhsl: internalcolor.Okhsl{H: 129.15, S: 99, L: 50},
	}
}

func (light) Green() Color {
	return Color{
		Name:  "Green",
		Index: 4,
		hex:   "#068c65",
		rgb:   color.RGBA{R: 6, G: 140, B: 101, A: 255},
		okhsl: internalcolor.Okhsl{H: 164.93, S: 99, L: 50},
	}
}

func (light) Turquoise() Color {
	return Color{
		Name:  "Turquoise",
		Index: 5,
		hex:   "#038981",
		rgb:   color.RGBA{R: 3, G: 137, B: 129, A: 255},
		okhsl: internalcolor.Okhsl{H: 187.1225, S: 99, L: 50},
	}
}

func (light) Cyan() Color {
	return Color{
		Name:  "Cyan",
		Index: 6,
		hex:   "#028696",
		rgb:   color.RGBA{R: 2, G: 134, B: 150, A: 255},
		okhsl: internalcolor.Okhsl{H: 209.315, S: 99, L: 50},
	}
}

func (light) Cerulean() Color {
	return Color{
		Name:  "Cerulean",
		Index: 7,
		hex:   "#0282ae",
		rgb:   color.RGBA{R: 2, G: 130, B: 174, A: 255},
		okhsl: internalcolor.Okhsl{H: 231.5075, S: 99, L: 50},
	}
}

func (light) Blue() Color {
	return Color{
		Name:  "Blue",
		Index: 8,
		hex:   "#0476db",
		rgb:   color.RGBA{R: 4, G: 118, B: 219, A: 255},
		okhsl: internalcolor.Okhsl{H: 253.7, S: 99, L: 50},
	}
}

func (light) Violet() Color {
	return Color{
		Name:  "Violet",
		Index: 9,
		hex:   "#764bfe",
		rgb:   color.RGBA{R: 118, G: 75, B: 254, A: 255},
		okhsl: internalcolor.Okhsl{H: 286.6025, S: 99, L: 50},
	}
}

func (light) Lavender() Color {
	return Color{
		Name:  "Lavender",
		Index: 10,
		hex:   "#b607d7",
		rgb:   color.RGBA{R: 182, G: 7, B: 215, A: 255},
		okhsl: internalcolor.Okhsl{H: 319.505, S: 99, L: 50},
	}
}

func (light) Pink() Color {
	return Color{
		Name:  "Pink",
		Index: 11,
		hex:   "#d30384",
		rgb:   color.RGBA{R: 211, G: 3, B: 132, A: 255},
		okhsl: internalcolor.Okhsl{H: 352.4075, S: 99, L: 50},
	}
}

func (light) RedBack() Color {
	return Color{
		Name:  "Red Back",
		Index: 12,
		hex:   "#f2d5d2",
		rgb:   color.RGBA{R: 242, G: 213, B: 210, A: 255},
		okhsl: internalcolor.Okhsl{H: 25.31, S: 51, L: 88},
	}
}

func (light) OrangeBack() Color {
	return Color{
		Name:  "Orange Back",
		Index: 13,
		hex:   "#f1d8c4",
		rgb:   color.RGBA{R: 241, G: 216, B: 196, A: 255},
		okhsl: internalcolor.Okhsl{H: 59.34, S: 51, L: 88},
	}
}

func (light) YellowBack() Color {
	return Color{
		Name:  "Yellow Back",
		Index: 14,
		hex:   "#e9ddb3",
		rgb:   color.RGBA{R: 233, G: 221, B: 179, A: 255},
		okhsl: internalcolor.Okhsl{H: 93.37, S: 51, L: 88},
	}
}

func (light) LimeBack() Color {
	return Color{
		Name:  "Lime Back",
		Index: 15,
		hex:   "#cfe6b8",
		rgb:   color.RGBA{R: 207, G: 230, B: 184, A: 255},
		okhsl: internalcolor.Okhsl{H: 129.15, S: 51, L: 88},
	}
}

func (light) GreenBack() Color {
	return Color{
		Name:  "Green Back",
		Index: 16,
		hex:   "#b9ead3",
		rgb:   color.RGBA{R: 185, G: 234, B: 211, A: 255},
		okhsl: internalcolor.Okhsl{H: 164.93, S: 51, L: 88},
	}
}

func (light) TurquoiseBack() Color {
	return Color{
		Name:  "Turquoise Back",
		Index: 17,
		hex:   "#b5e9e3",
		rgb:   color.RGBA{R: 181, G: 233, B: 227, A: 255},
		okhsl: internalcolor.Okhsl{H: 187.1225, S: 51, L: 88},
	}
}

func (light) CyanBack() Color {
	return Color{
		Name:  "Cyan Back",
		Index: 18,
		hex:   "#bbe6ee",
		rgb:   color.RGBA{R: 187, G: 230, B: 238, A: 255},
		okhsl: internalcolor.Okhsl{H: 209.315, S: 51, L: 88},
	}
}

func (light) CeruleanBack() Color {
	return Color{
		Name:  "Cerulean Back",
		Index: 19,
		hex:   "#c5e2f2",
		rgb:   color.RGBA{R: 197, G: 226, B: 242, A: 255},
		okhsl: internalcolor.Okhsl{H: 231.5075, S: 51, L: 88},
	}
}

func (light) BlueBack() Color {
	return Color{
		Name:  "Blue Back",
		Index: 20,
		hex:   "#cfdff3",
		rgb:   color.RGBA{R: 207, G: 223, B: 243, A: 255},
		okhsl: internalcolor.Okhsl{H: 253.7, S: 51, L: 88},
	}
}

func (light) VioletBack() Color {
	return Color{
		Name:  "Violet Back",
		Index: 21,
		hex:   "#dbdaf3",
		rgb:   color.RGBA{R: 219, G: 218, B: 243, A: 255},
		okhsl: internalcolor.Okhsl{H: 286.6025, S: 51, L: 88},
	}
}

func (light) LavenderBack() Color {
	return Color{
		Name:  "Lavender Back",
		Index: 22,
		hex:   "#e9d5ee",
		rgb:   color.RGBA{R: 233, G: 213, B: 238, A: 255},
		okhsl: internalcolor.Okhsl{H: 319.505, S: 51, L: 88},
	}
}

func (light) PinkBack() Color {
	return Color{
		Name:  "Pink Back",
		Index: 23,
		hex:   "#f1d4df",
		rgb:   color.RGBA{R: 241, G: 212, B: 223, A: 255},
		okhsl: internalcolor.Okhsl{H: 352.4075, S: 51, L: 88},
	}
}

func (light) Base0() Color {
	return Color{
		Name:  "Base 0",
		Index: 24,
		hex:   "#f5f3f1",
		rgb:   color.RGBA{R: 245, G: 243, B: 241, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 12, L: 96},
	}
}

func (light) Base1() Color {
	return Color{
		Name:  "Base 1",
		Index: 25,
		hex:   "#edeae7",
		rgb:   color.RGBA{R: 237, G: 234, B: 231, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 11, L: 93},
	}
}

func (light) Base2() Color {
	return Color{
		Name:  "Base 2",
		Index: 26,
		hex:   "#e6e2de",
		rgb:   color.RGBA{R: 230, G: 226, B: 222, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 10, L: 90},
	}
}

func (light) Base3() Color {
	return Color{
		Name:  "Base 3",
		Index: 27,
		hex:   "#d6d1cb",
		rgb:   color.RGBA{R: 214, G: 209, B: 203, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 9, L: 84},
	}
}

func (light) Base4() Color {
	return Color{
		Name:  "Base 4",
		Index: 28,
		hex:   "#c6c0ba",
		rgb:   color.RGBA{R: 198, G: 192, B: 186, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 8, L: 78},
	}
}

func (light) Base5() Color {
	return Color{
		Name:  "Base 5",
		Index: 29,
		hex:   "#b6b0a9",
		rgb:   color.RGBA{R: 182, G: 176, B: 169, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 7, L: 72},
	}
}

func (light) Over0() Color {
	return Color{
		Name:  "Over 0",
		Index: 30,
		hex:   "#a5a09a",
		rgb:   color.RGBA{R: 165, G: 160, B: 154, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 6, L: 66},
	}
}

func (light) Over1() Color {
	return Color{
		Name:  "Over 1",
		Index: 31,
		hex:   "#95908b",
		rgb:   color.RGBA{R: 149, G: 144, B: 139, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 5, L: 60},
	}
}

func (light) Over2() Color {
	return Color{
		Name:  "Over 2",
		Index: 32,
		hex:   "#84817c",
		rgb:   color.RGBA{R: 132, G: 129, B: 124, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 4, L: 54},
	}
}

func (light) Text0() Color {
	return Color{
		Name:  "Text 0",
		Index: 33,
		hex:   "#4d4d4c",
		rgb:   color.RGBA{R: 77, G: 77, B: 76, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 1, L: 33},
	}
}

func (light) Text1() Color {
	return Color{
		Name:  "Text 1",
		Index: 34,
		hex:   "#5f5e5c",
		rgb:   color.RGBA{R: 95, G: 94, B: 92, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 2, L: 40},
	}
}

func (light) Text2() Color {
	return Color{
		Name:  "Text 2",
		Index: 35,
		hex:   "#726f6c",
		rgb:   color.RGBA{R: 114, G: 111, B: 108, A: 255},
		okhsl: internalcolor.Okhsl{H: 67.8475, S: 3, L: 47},
	}
}
